BASELINE_INTERVAL=30
ATTACK_INTERVAL=30

CYCLE_MODE="sequential"

ENABLED_SCENARIOS="web-recon web-sqli web-xss web-bruteforce ssh-brute sangfor-logs waf-logs fim-webshell google-site-verification web-scan info-disclosure seo-cloaking"

INTENSITY="high"

NORMAL_INJECT="yes"
NORMAL_LINES_LOW=5
NORMAL_LINES_MEDIUM=12
NORMAL_LINES_HIGH=25

ATTACK_LINES_LOW=15
ATTACK_LINES_MEDIUM=30
ATTACK_LINES_HIGH=100

AGENTS_SHARED="shared-hosting"
AGENTS_MULTI="multi-site"
SYSLOG_TARGET="wazuh-manager"
SYSLOG_PORT="1514"
